projects:
    name: ocr
    version: 1.2.0
    image_name: ocr:v1.2.0

log:
    log_path: /data/logs/linkedsee/
    log_clear_path: log_clear.conf

shell_scripts:
    - 'sh xxx.sh'

database_init:
    database_name: 'ocr'
    table_name: '0'
    datas:
        table_name:
            - field_name: 'xxx'
            - field_data: 'xxx'
    migrations:
        script:
            - 'python manage.py migrate'
        links:
            - 'curl ${LINKEDSEEIP}:9001/api/v1/database_init 200'